---
abstract: 'Generate text documentation for a package from Rinci metadata'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Perinci::Examples: 0
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-To-Text
requires:
  Data::Dump::OneLine: 0
  Locale::Maketext::Lexicon: 0
  Locale::Maketext::Lexicon::Gettext: 0
  Log::Any: 0
  Moo: 0
  Perinci::Access: 0.25
  Perinci::Access::InProcess: 0.38
  Perinci::Object: 0.11
  Perinci::Sub::To::FuncBase: 0
  Perinci::Sub::To::Text: 0
  Perinci::ToUtil: 0
  Rinci: v1.1.11
  SHARYANTO::Role::Doc::Section: 0.53
  SHARYANTO::Role::Doc::Section::AddTextLines: 0.53
  SHARYANTO::Role::I18N: 0.15
  SHARYANTO::Role::I18NRinci: 0
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Perinci-To-Text/
  repository: http://github.com/sharyanto/perl-Perinci-To-Text
version: 0.20
